simpleDict={
    "class":{
        "student":{
            "name":"Mike",
            "marks":{
                "phisics":70,
                "history":80
            }
        }
    }
}
print(simpleDict["class"]["student"]["marks"]["history"])